### ISSUE TITLE
feat: separate swap amount settings for luna and bluna

### ISSUE THREAD

**Issue by AaronCQL** [AaronCQL/bluna-bot#1]
Separate current `minSwapAmount` and `maxSwapAmount` to 4 different settings: `minLunaSwapAmount`, `maxLunaSwapAmount`, `minBlunaSwapAmount`, and `maxBlunaSwapAmount`.

This allows for more use cases like limiting the max amount of luna to be swapped, but always allowing all bluna to be swapped back to luna.

**Comment by avocardow** [comment]
Wow this is a great idea. Love it. Nice feature addition

**Comment by AaronCQL** [comment]
> Wow this is a great idea. Love it. Nice feature addition

Credits for the idea goes to you, thanks mate!
